name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch if it's named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy MkDocs
        run: |
          mkdocs gh-deploy --force
